main: com.github.kraftlegos.Main
version: 1.3
author: Kraft
name: SkyFlag
description: Skyflag minigame plugin!
commands:
  join:
    description: Let's you join a game!
  forcestart:
    description: Force starts a game!
  end:
    description: Ends a game abruptly!
  shout:
    description: Let's you send a message to all teams!
  forceadd:
    description: Forcibly adds a player to your game!

permissions:
  skyflag.forceop:
    description: Allows you to forcestart a game
    default: op
  skyflag.end:
    description: Allows you to end a game
    default: op
  skyflag.forceadd:
    description: Allows you to use /forceadd
    default: op